on: pull_request

name: Inspections
jobs:
  runPHPCSInspection:
    name: PHPCS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.sha }}
        
    - name: Run PHPCS
      uses: rtCamp/action-phpcs-code-review@v3
      env:
        GH_BOT_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
      with:
        args: "WordPress,WordPress-Core,WordPress-Docs"
